Entrega a2
selsa-inube/bootcamp-may pull request #74
Opened 2024-05-24 22:41 UTC by SelsaErojas

Entrega actividad a2

2024-06-03 19:36 UTC, carin91 requested changes

2024-06-06 16:20 UTC, SelsaErojas commented on src/Er/a2-markup-readme
> -    </div>
Se realiza ajuste y se crean los links de manera adecuada

2024-06-06 16:21 UTC, SelsaErojas commented on src/Er/a2-markup-readme
> -    </div>
Se corrigen los estilos creados

2024-06-06 16:21 UTC, SelsaErojas commented on src/Er/a2-markup-readme
> +    </div>
Se corrige el documento dejando solo estructura html

2024-06-06 16:58 UTC, merged